### ISSUE TITLE
pretty-format/build/index.d.ts(7,13): '=' expected.  TS1005 관련

### ISSUE THREAD

**Issue by shimpark** [rajephon/douzone-payslip-viewer#2]
typescript 버전이 낮아서 그런가 해서...
yarn global add typescript@latest 
적용했습니다. 하지만 여전히 오류가 발생되더라고요. (windows)

Failed to compile
D:/SourceCode/ReactJS/douzone-payslip-viewer-master/node_modules/pretty-format/build/index.d.ts
TypeScript error in D:/SourceCode/ReactJS/douzone-payslip-viewer-master/node_modules/pretty-format/build/index.d.ts(7,13):
'=' expected.  TS1005

     5 |  * LICENSE file in the root directory of this source tree.
     6 |  */
  >  7 | import type { NewPlugin, Options, OptionsReceived } from './types';
       |             ^
     8 | export type { Colors, CompareKeys, Config, Options, OptionsReceived, OldPlugin, NewPlugin, Plugin, Plugins, PrettyFormatOptions, Printer, Refs, Theme, } from './types';
     9 | export declare const DEFAULT_OPTIONS: Options;
    10 | /**
This error occurred during the build time and cannot be dismissed.

**Comment by shimpark** [comment]
죄송합니다 . yarn 으로 해야 하는데 npm install 로 해서 발생된 부분이었습니다. ㅜㅜ

**Comment by rajephon** [comment]
이슈 클로즈 하겠습니다. 혹 문제 생기면 언제든 남겨주세요 🙂
